saleor/cli

- src/cli.ts
To prevent misleading package update command
> Use isGlobal flag for update-notifier

- package.json
I want to merge this because this PR adds links in `package.json` that make it possible to display links inside npm pacakge page
For example see [Material UI](https://www.npmjs.com/package/@material-ui/core):
> Add links for npm page

- src/cli/app/deploy.ts
That's blocking https://github.com/saleor/saleor-app-template/pull/56
(separate question is where actually point, when registering app in denver)
> Temporary support of both - new and old envnames

- pnpm-lock.yaml
- src/cli/app/deploy.ts
- src/lib/vercel.ts
The app installation must accept the project domain as the Manifest URL and not the deployment, e.g. you may want to `git push` during development and the Saleor dashboard should reference the newest deployment, thus using the project domain.
This PR also fixes how URLs for Next Steps are displayed; fixes #250
> Use the project domain, not deployment domain

- src/cli.ts
* For broader runtime environment compatibility. Seems some environments
doesn't split the argument string which may be the cause of `No such
file or directory` error
> Move no-warnings flag to env var

- .gitignore
- src/cli/app/tunnel.ts
I'd like to have this feature, because as a new user I wasn't aware it always looks for `:3000`
My app was running on `3001` and I didn't know there was some detached process on `:3000` causing a bug.
> Display active local port that is tunnelling

- src/cli/app/create.ts
- src/cli/app/deploy.ts
- src/lib/common.ts
- src/lib/vercel.ts
It removes the `.env` file requirement for `app create` and `app deploy` commands. No environment variables from the `.env` file are required for the aforementioned commands.
In the same time the `app create` doesn't require 
- 
- create an app `saleor app create` - in the created folder there should be no `.env` file, and there should be no prompt for the organization and the environment
- deploy an app `saleor app deploy` - the `.env` file should not be required to deploy an app
> Remove `.env` file requirement for `app` commands

- src/cli/app/deploy.ts
- src/lib/util.ts
**I want to merge this PR because: **
The name from `package.json` have to be the same as git repository name
- https://github.com/saleor/saleor-cli/issues/341
- create a saleor app `saleor app create`
- deploy an app `saleor app deploy`
- modify the name in `package.json`
- deploy an app `saleor app deploy`
> Verify name for `app deploy`

- src/cli/dev/info.ts
**I want to merge this PR to** have the CLI version in one place along with the OS versions.
- NA
- NA
> Add the version explicitly to `dev info` output

- package.json
- pnpm-lock.yaml
- src/cli.ts
- src/lib/config.ts
- src/lib/util.ts
**I want to merge this PR to** use a custom implementation for the version update notifier. It's needed to make the CLI bundling work.
- #253 
-
> Replace `update-notifier` with a custom implement

- package.json
**I want to merge this PR to** install only `got` for the `scripts/`
- 
-
> Allow `got` as dep in the prod build

- src/lib/environment.test.ts
**I want to merge this PR because: **
It adds endpoint handlers for both staging and production. This enables test to be run on any environment.
- 
-
> Define both prod & staging handlers for environment test

- docs/status.md
- src/cli.ts
- src/cli/info.ts
- src/cli/status.ts
**I want to merge this PR** to provide the login status for the systems that CLI depends on.
- #334 
- `saleor status`
> Add `status` command for better DX

- src/middleware/index.ts
This PR disables output for organization and environment info in the middleware in case the `json` flag is set. This enables the JSON output to be parsed.
- 
-
> Skip middleware info for json output

- src/cli/app/deploy.ts
- src/cli/app/token.ts
- src/cli/checkout/deploy.ts
- src/cli/env/create.ts
- src/cli/storefront/deploy.ts
- src/lib/common.ts
- src/lib/deploy.ts
- src/lib/util.ts
- src/lib/vercel.ts
- src/types.ts
It updates and unifies the deploy commands. 
It uses the `react-storefront` repository for checkout deployment.
It removes the `.env` dependency for deployment.
It unifies the deployment process.
It introduces `contentBox` instead of boxen ones for better handling of long texts/URLs
`saleor app deploy`
`saleor checkout deploy` 
`saleor storefront deploy`
- 
-
> Update deploy commands

- src/cli/dev/info.ts
- it fixes the path import for `dev info` with `esbuild` setup
- #383 
-
> Fix the path for `dev info`

- src/cli/app/tunnel.ts
- it adjusts the tunnel binary location for the new bundling approach introduced with `esbuild`
- NA
-
> Adjust `app tunnel` vendor for new bundling

- src/cli/app/deploy.ts
- src/cli/checkout/deploy.ts
- src/cli/storefront/deploy.ts
- src/lib/deploy.ts
- src/types.ts
**I want to merge this PR because:**  is enables to skip repository creation prompt on Github. Use `--no-github-prompt` with `deploy` commands.
- [Enable non-interactive mode for deploy commands](https://github.com/saleor/saleor-cli/issues/386)
Run one of commands below with `--no-github-prompt` argument
- `saleor app deploy`
- `saleor storefront deploy`
- `saleor checkout deploy`
> Allow to skip create GH repo prompt

- test/functional/app/deploy.test.ts
- test/functional/checkout/deploy.test.ts
- test/functional/environment/show.test.ts
- test/functional/storefront/deploy.test.ts
- test/helper.ts
- it introduces set of functional tests for `deploy` commands. Currently configured to run only on local machine.
- https://github.com/saleor/saleor-cli/issues/260
- `pnpm vitest`
> Introduce set of functional tests for `deploy` commands

- docs/prepare.md
- it introduces documentation for `saleor dev` commands 
- https://github.com/saleor/saleor-cli/issues/330
- https://github.com/saleor/saleor-cli/issues/223
- NA
> Document `dev` commands in docs

- src/cli/env/create.ts
- It allows to skip dashboard admin email prompt for `environment creation`
- [405](https://github.com/saleor/saleor-cli/issues/405)
- `saleor storefront create --demo`
> Allow to skip dashboard admin email for `env create`

- src/cli/app/create.ts
- src/cli/storefront/create.ts
- src/lib/download.ts
- it sets the downloaded repository to specific commit hash
- https://github.com/saleor/saleor-cli/issues/298
- `saleor app create` - commit hash `a5caa3f2580ad075faeee9d4a2125e77bc60f6d8`
- `saleor store create` - commit hash `659ed312a4930e38150276e0ea714efc6ccc22e3`
> Use commit hash for `store create` & `app create`

- src/middleware/index.ts
- it provides a more comprehensive way to validate the instance URL provided as an argument
- https://github.com/saleor/saleor-cli/issues/321
- provide a valid URL
- provide invalid URL
- provide an URL with a pathname e.g. `https://foo.saleor.cloud/graphql/`
- provide an URL without protocol
> Fix the URL parsing for the instance arg

- src/middleware/index.ts
- it fixes the `ping` arguments for different OSes
- #428 
- `saleor info` on Ubuntu
> Fix args for `ping` on different OSes

- src/middleware/index.ts
- It fixes the online checker behaviour in GitHub Actions. `ping` [doesn't work in GitHub Actions](https://github.com/actions/runner-images/issues/1519#issuecomment-683790054)
- #428 
- Run any CLI command with `CI` set
> Fix the online check for GitHub Actions

- src/lib/common.ts
It simplifies app installation by removing the app name input prompt. The name is taken from manifest or from argv `app-name`
- https://github.com/saleor/saleor-cli/issues/264
- `saleor app install`
> Use name from manifest or app-name from argv for `app install`

- .github/workflows/tests-nightly.yml
- it removes the pnpm cache as it stales the installation process for all actions 
- NA
- NA
> Remove cache for tests-nightly

- src/cli/app/create.ts
- src/cli/storefront/create.ts
- src/config.ts
- src/lib/download.ts
- src/lib/util.ts
- src/types.ts
- it aligns the `* create` with how Git clone work; thus, it's only possible to specify a branch or a tag of a Git repository
- it adds `--template` (aliased with`-t`) to specify custom GitHub repo. 
- #430 
- #449 
- `app create`
- `app create --branch <branch name>`
- `app create --branch <tag name>`
- `app create --template saleor/saleor-app-template --branch add-typings`
- detect if given repo is a Saleor App template
> Align project creation with Git clone

- docs/app.md
- src/cli/app/permission.ts
- src/cli/app/token.ts
- src/types.ts
- 
- https://github.com/saleor/saleor-cli/issues/352
- `saleor app permission --environment=env --app-id=app --permissions=MANAGE_USERS --permissions=MANAGE_STAFF`
> Allow `app permissions` to run non interactive

- src/cli/backup/create.ts
- src/cli/backup/list.ts
- src/cli/env/list.ts
- src/cli/env/promote.ts
- src/cli/job/list.ts
- src/cli/organization/list.ts
- src/cli/organization/permissions.ts
- src/cli/project/list.ts
- src/cli/project/remove.ts
- src/cli/webhook/list.ts
- it enables JSON output for more commands
- NA
- `saleor backup create --json`
- `saleor backup list --json`
- `saleor env list --json`
- `saleor env promote --json`
- `saleor job list --json`
- `saleor organization list --json`
- `saleor organization permissions --json`
- `saleor project list --json`
- `saleor webhook list --json`
> Enable JSON output for more commands

- src/cli/app/deploy.ts
Saleor apps, especially template is looking for `APL` env variable. Locally it can be set but in vercel it must be `APL=vercel`
https://github.com/saleor/saleor-app-template/blob/canary/saleor-app.ts
- 
-
> Add APL=vercel env variable when deploying app

- .github/workflows/clear-staging-cloud.yml
- .github/workflows/deployment-tests-nightly.yml
- test/functional/checkout/deploy.test.ts
- test/functional/storefront/deploy.test.ts
It introduces additional workflows for nightly tests
- deployment-tests-nightly to run tests for deployment commands (`app deploy`, `checkout deploy`, `storefront deploy`
- clear-staging-cloud to remove all projects (including environments)
- #436 
-
> Additional workflows for GitHub Actions

- .github/workflows/clear-staging-cloud.yml
- .github/workflows/deployment-tests-nightly.yml
- package.json
- pnpm-lock.yaml
- test/functional/tunnel.test.ts
- It kills the spawned subprocesses with tunnel command. Hence all the processes which were stared are closed and the created app -> `tunnel-app` can be deleted
- #451 
- `RUN_FUNCTIONAL_TESTS=true pnpm vitest run  test/functional/tunnel.test.ts `
> Kill subprocesses for tunnel test

- src/middleware/index.ts
As initially proposed by @2can and proved by @lkostrowski :)
- it makes the telemetry call non-blocking the middleware stack, yet the potential errors are still handled
- #502 
- NA
> Make telemetry call non-block middleware stack

- src/cli/env/switch.ts
- It allows passing the environment name as an argument to the `environment switch` command.
- #514
- `saleor env switch 'name of your environment'`
> Accept the env name in the `env switch`

- src/cli/env/create.ts
- it makes the domain slugify lowercase. The API requires the domain to be lowercase, hence the change should prevent  the `Label is invalid` error 
- 
-
> Use toLowerCase for domain

- docs/app.md
- src/cli/app/create.ts
- src/lib/download.ts
- src/types.ts
- it introduces the `--example` arg for the `app create` command. It allows to choose the example repository from [app-examples](https://github.com/saleor/app-examples) as the app template
- #489 
- saleor app create --example
- saleor app create --example external-webhook
> Introduce `--example` flag for the `app create`

- src/cli/app/create.ts
- It extends the summary for `saleor app create` with the tip about `saleor app tunnel`
- #478
- `saleor app create`
> Inform user about `saleor app tunnel` in the `app create` summary

- src/cli/app/permission.ts
- src/cli/app/token.ts
- src/cli/backup/index.ts
- src/cli/backup/restore.ts
- src/cli/trigger.ts
- src/cli/webhook/create.ts
- src/cli/webhook/edit.ts
- src/cli/webhook/index.ts
- src/cli/webhook/list.ts
- src/cli/webhook/update.ts
- src/lib/common.ts
- src/lib/environment.test.ts
- src/lib/environment.ts
- src/lib/util.ts
- src/middleware/index.ts
- it eliminates the direct calls to get the API instance endpoint. Instead, use the middlewares and harmonise this approach.
- #523 
- NA
> Eliminate direct calls for API endpoint

- README.md
- it adds a section in README describing the release process for the CLI
- #456 
-
> Add the release process to `README`

- src/lib/util.ts
- it skips the select prompt if only 1 option is present and allowCreation is false. It's a change on `createPrompt` so it will influence
- `promptWebhook`
- `promptSaleorApp`
- `promptCompatibleVersion`
- `promptDatabaseTemplate`
- `promptProject`
- `promptEnvironment`
- `promptOrganization`
- `promptPlan`
- `promptRegion`
- `promptOrganizationBackup`
- #468 
-
> Preselect prompts if 1 option present

- src/cli/app/tunnel.ts
- src/generated/graphql.ts
- src/graphql/SaleorAppsInstallations.graphql
- src/lib/common.ts
- it displays the app entry point in the Dashboard for `app tunnel`. 
This process needs some changes in the core side as seems to me there is no 100% correct way to identify id that the app got assigned. 
1.`AppInstall` mutation returns `AppInstallation`  which contains `appInstallation` id. 
2. Query `appsInstallations` provides the information about the ongoing installations (no app id yet). As soon as the installation is  "SUCCEEDED" it's no longer available in this query.
3. In order to get the app id query `apps` is needed, it returns the app id but at the same time there is no connection to the `AppInstallation` so we can't be 100% sure the app we assessed by installation date, name and manifest URL is the one.
- #469 
- saleor app tunnel
- saleor app tunnel --force-install
> Print app URL to Dashboard for `app tunnel`

- src/cli/github/login.ts
- src/cli/info.ts
- src/cli/login.ts
- src/cli/status.ts
- src/cli/vercel/login.ts
- src/lib/config.ts
- it verifies Github & Vercel tokens' validity
- it displays user data for tokens - email and name
- it stores and displays the current environment for which user is logged in for `info` and `status` commands
- it prints `success` for `vercel login` & `github login`
- #493
- `saleor info`
- `saleor status`
> Status improvements - display env, verify auth tokens

- src/cli/app/install.ts
- src/cli/app/list.ts
- src/cli/app/permission.ts
- src/cli/app/token.ts
- src/cli/app/tunnel.ts
- src/cli/app/uninstall.ts
- src/cli/backup/index.ts
- src/cli/env/clear.ts
- src/cli/env/populate.ts
- src/cli/job/list.ts
- src/cli/webhook/index.ts
- src/middleware/index.ts
- src/types.ts
- it introduces checks for 
- environment graphql endpoint availability - `useAvailabilityChecker` - which checks `maintenance_mode` and `disabled` flags
- environment db layer availability  - `useBlockingTasksChecker` which checks `blocking_tasks_in_progress` flag
- #364 
- trigger the maintenance mode on the environment and run some of the webhook commands eg `saleor webhook list`
- `saleor backup restore` followed by one of `saleor env populate`, `saleor env clear`,  and any of `saleor backup` commands
> Check & handle env status flags

- src/cli/configure.ts
- src/cli/login.ts
- It catches `ENOENT` error which indicates the headless mode. In such case the `configure` command should be used instead.
- #548 
- `saleor login` in the headless environment
> Detect headless mode for `login`

- src/cli/webhook/create.ts
- src/graphql/doWebhookCreate.ts
- src/types.ts
- it adds simple ` targetUrl` validation and errors handling for `webhook create` command
- #415 
- `saleor webhook create`
> Validate targetUrl for `webhook create`

- docs/app.md
- pnpm-lock.yaml
- src/cli.ts
- src/cli/app/tunnel.ts
- src/lib/util.ts
- it adds `ngrok` as a failover for the `app tunnel` command via the `--use-ngrok` command-line option
- #504 
- `saleor app tunnel --use-ngrok`
> Use `ngrok` failover for `app tunnel`

- src/cli.ts
- It allows yargs to use a width longer than 80 characters in the terminal
- NA
-
> Allow yargs to use width of more than 80 chars

- src/cli/app/tunnel.ts
- it adds the missing descriptions for options of the `app tunnel` command
- #568
- NA
> Add missing desc for `app tunnel` options

- .gitignore
- package.json
- pnpm-lock.yaml
- it adds type coverage with a report generation
- #544
- `pnpm typecov`
- `pnpm typecov-report`
> Add type coverage + type report

- src/lib/instance.ts
- it uses the environment domain for environment inference while the instance parameter is provided
- #569 
- `saleor app install --instance=SALEOR_INSTANCE_URL`
> Use domain to verify env presence for instance param

- src/middleware/index.ts
- it changes the message if the environment was not found
- #558 
- `saleor env show --environment SOME_RANDOM_STRING`
> Improve env not found message in the middleware

- package.json
- it narrows down `dist` files to `saleor.json`. Recently added `--sourcemap` param generates a source map which shouldn't be put into the release package.
- 
-
> Narrow down files for package

- docs/README.md
- src/cli/app/deploy.ts
- src/cli/app/tunnel.ts
- src/cli/checkout/deploy.ts
- src/lib/common.ts
- src/lib/deploy.ts
- src/lib/util.ts
- src/types.ts
- it allows to define manifest path for `app tunnel` & `app deploy` commands
- https://github.com/saleor/saleor-app-sdk/issues/54
- `saleor app tunnel --manifest-path=/manifest`
- `saleor app deploy --manifest-path=/manifest`
> Configurable app manifest path

- test/helper.ts
- as the `stderr` may contain non error data,  exit code is the proper error indicator
- https://github.com/saleor/saleor-cli/actions/runs/3644875838
-
> Use exit code as error indicator

- src/lib/common.ts
- it sets proper order of arguments for buildManifestURL
- 
- `saleor app deploy`
> Fix argumets order for buildManifestURL

- docs/README.md
- src/cli.ts
- src/cli/login.ts
- src/cli/open.ts
- src/types.ts
It opens the browser with docs or instance page
- It adds an `open` command which opens the browser with docs or instance page
- 
- `saleor open`
- `saleor open dashboard`
- `saleor open api`
- `saleor open docs`
> Add `open` command

- docs/README.md
- src/cli/webhook/dryRun.ts
- src/cli/webhook/index.ts
- src/graphql/doWebhookDryRun.ts
- src/types.ts
- it introduces `webhook dry-run` command
- NA
- `saleor webhook dry-run`
- `saleor webhook dry-run --object-id='UHJvZHVjdDo3Mg=='`
- `saleor webhook dry-run --query='subscription { event { ... on ProductCreated { product { id name } } } }'`
> Add `webhook dry-run` command

- src/lib/common.ts
It fixes saleor app folder validation when `.mjs` extension is used (e.g. `next.config.mjs` instead of `next.config.js`)
- Run `saleor app tunnel` in folder with app that uses `next.config.mjs`
> Fix `saleor app` folder validation when mjs extension is used

- package.json
- pnpm-lock.yaml
- src/cli/app/list.ts
- src/cli/backup/list.ts
- src/cli/configure.ts
- src/cli/dev/info.ts
- src/cli/env/list.ts
- src/cli/info.ts
- src/cli/job/list.ts
- src/cli/login.ts
- src/cli/organization/list.ts
- src/cli/project/list.ts
- src/cli/webhook/list.ts
- it reverts `oclif` to `1.x` as it messes up the bundling with `esbuild`
- NA
- NA
> Revert `oclif` to `1.x`

- src/cli/webhook/create.ts
- it allows to pick syncEvents or asyncEvents for webhook create
- NA
- `saleor webhook create`
> syncEvents or asyncEvents for webhook create

- src/cli.ts
- it allows to run only for Node 16+ and warn for odd versions
- NA
-
> Run only for Node 16+ and warn for odd versions

- src/cli/login.ts
- instead of redirecting to the Saleor Cloud it shows a success page after login
- [#624](https://github.com/saleor/saleor-cli/issues/624)
- `saleor login`
> Custom success page instead of redirect

- src/cli/env/remove.ts
- src/lib/util.ts
- it aligns the `env create` with the recent changes in Saleor Cloud regarding the environment creationg
- NA
-
> Align the `env create` with Cloud speed up

- src/cli/github/login.ts
- src/cli/login.ts
- src/cli/vercel/login.ts
- src/lib/util.ts
- it shows a custom success page after successful integration with Vercel or Github
- NA
- `saleor vercel login`
- `saleor github login`
> Show custom page instead of redirect for Vercel & Github login

- docs/README.md
- src/cli/env/populate.ts
- src/cli/env/remove.ts
- src/lib/util.ts
- it adds a confirm prompt for `saleor env populate` command
- it adds `useEnvironment` middleware to allow to pick the environment in case of blank parameter or use environment name
- NA
- `saleor env populate`
> Add prompt and useEnvironment middleware for `saleor env populate`

- src/lib/util.ts
- it properly sorts the available Saleor versions for the `environment create` command 
- NA
- `saleor env create`
> Sort for promptCompatibleVersion

- docs/README.md
- src/cli/env/create.ts
- src/lib/util.ts
- it removes the outdated ability to deploy `react-storefront` starter to Vercel after successful environment creation 
- https://github.com/saleor/saleor-cli/issues/532
- `saleor env create`
> Remove deployment prompt from `env create`

- docs/README.md
- src/cli/env/create.ts
- src/lib/index.ts
- test/functional/environment/create.test.ts
- it removes `email` option used to setup the Dashboard acccess
- it adds example commands
- it adds `skip-restrict` to the options list and unifies options naming
- #649 
- `saleor env create my-env-name`
> Remove access prompt for `env create`, update options & examples

- docs/README.md
- src/cli/backup/create.ts
- it allows entering backup name interactively 
- it adds examples 
- NA
- `saleor backup create`
> Add name prompt & examples for `backup create` command

- .gitignore
- package.json
- pnpm-lock.yaml
- it pushes source maps to Sentry in post publish hook
- NA
- `pnpm publish`
> Upload sourcemaps to Sentry after publish

- src/cli/github/login.ts
- src/lib/config.ts
- src/types.ts
- it switches from `Web Application flow` to  `Device flow` for GitHub OAuth
- #673
- `saleor github login`
> Switch to device flow for `github login`

- docs/README.md
- src/cli/env/auth.ts
- src/cli/env/index.ts
- src/cli/env/maintenance.ts
- src/cli/env/update.ts
- src/lib/index.ts
- src/types.ts
- test/__snapshots__/vercel.test.ts.snap
- test/functional/environment/show.test.ts
- test/functional/environment/update.test.ts
This PR introduces additional commands for environment management. It adds 
- `saleor env update` to edit environment name
- `saleor env auth` to manage basic auth protection on the environment
- `saleor env maintenance` to manage maintenance mode on the environment  
- #679
- `saleor env update`
- `saleor env auth`
- `saleor env maintenance`
> Commands to trigger updates on the environment

- src/cli/env/maintenance.ts
- test/functional/environment/auth.test.ts
- test/functional/environment/maintenance.test.ts
- test/functional/environment/update.test.ts
- test/helper.ts
- it fixes the prompt logic for the prompt in the `env maintenance` command
- it reorganizes the tests connected with environment update
- NA
- `saleor env maintenance`
> Fix `env maintenance` prompt

- docs/README.md
- src/cli/env/cors.ts
- src/cli/env/index.ts
- src/cli/env/origins.ts
- src/cli/webhook/create.ts
- src/lib/environment.ts
- src/lib/util.ts
- test/functional/environment/cors.test.ts
- test/functional/environment/create.test.ts
- test/functional/environment/maintenance.test.ts
- test/functional/environment/origins.test.ts
- test/functional/environment/update.test.ts
- test/helper.ts
This PR introduces additional commands for environment management. It adds
- `saleor env cors` to manage CORS in the environment
- `saleor env origins` to manage client-trusted origins in the environment
- #688 
- #689 
- `saleor env cors`
- `saleor env origins`
> Add `env cors` & `env origins` commands

- src/cli/env/cors.ts
- it fixes the `env cors` prompt caused by strange handling of choice options by enquirer
- if extracts to const the `Add a new CORS origin`
- #688 
- `saler env cors`
> Fix `env cors` prompt

- .husky/pre-commit
- docs/README.md
- docs/cli/commands/environment.mdx
- src/cli/env/origins.ts
- it changes the `origin` option to `origins` as a unification to plural form for array options
- NA
- `saleor env origins --origins=https://yourdomain.com`
> Unify array option naming

- docs/README.md
- docs/cli/commands/app.mdx
- docs/cli/commands/backup.mdx
- docs/cli/commands/environment.mdx
- src/cli/app/create.ts
- src/cli/app/list.ts
- src/cli/app/permission.ts
- src/cli/app/remove.ts
- src/cli/app/token.ts
- src/cli/app/uninstall.ts
- src/cli/backup/list.ts
- src/cli/backup/remove.ts
- src/cli/backup/restore.ts
- src/cli/backup/show.ts
- src/cli/env/clear.ts
- src/cli/env/create.ts
- src/cli/storefront/deploy.ts
- src/cli/trigger.ts
- src/cli/webhook/create.ts
- src/cli/webhook/dryRun.ts
- src/cli/webhook/edit.ts
- src/cli/webhook/list.ts
- src/cli/webhook/update.ts
- src/lib/common.ts
- src/lib/environment.test.ts
- src/lib/queryEnvironment.ts
- src/lib/util.ts
- src/middleware/index.ts
- src/types.ts
- test/functional/environment/origins.test.ts
- it changes the` instance` URL to contain `/graphql/` suffix for the Saleor Cloud environments. This way both custom `instance` passed as argument and the instance based on the Cloud indicates a graphql endpoint.
- it extends commands with `examples `  
- NA
-
> Use instance with `graphql` suffix, add examples

- src/cli/storefront/create.ts
- it extends the `storefront create` command with additional output to help finalization of the setup process
- NA
- `saleor storefront create`
> Improve the `storefront create` output

- docs/README.md
- docs/cli/commands/environment.mdx
- src/cli/env/create.ts
- it allows to skip webhooks update prompt when creating a new environment using the `restore-from` option
- #700 
- `saleor-dist env create ... --project=... --database=snapshot --restore-from=... --saleor=saleor-master-staging --domain=...  --skip-restrict --skip-webhooks-update`
> Allow to skip webhooks update when using `env create`

- src/middleware/index.ts
- it allows the use `SALEOR_CLI_TOKEN` variable for communication with Saleor Cloud. It can be useful in CI or headless environments. This environment variable takes precedence over the config file.
- NA
- set `SALEOR_CLI_TOKEN` environment variable
> Read token from environment variable

- docs/README.md
- docs/cli/commands/app.mdx
- docs/cli/commands/backup.mdx
- docs/cli/commands/environment.mdx
- src/cli/app/create.ts
- src/cli/app/install.ts
- src/cli/app/permission.ts
- src/cli/app/remove.ts
- src/cli/app/tunnel.ts
- src/cli/app/uninstall.ts
- src/cli/backup/create.ts
- src/cli/backup/index.ts
- src/cli/backup/list.ts
- src/cli/backup/remove.ts
- src/cli/backup/restore.ts
- src/cli/backup/show.ts
- src/cli/env/clear.ts
- src/cli/env/create.ts
- src/cli/storefront/deploy.ts
- src/lib/index.ts
- src/lib/util.ts
- src/middleware/index.ts
- src/types.ts
- test/functional/backup/restore.test.ts
- it switches backup commands to use the organization backup endpoint. It eliminates the need for the environment with those commands, making them more convenient.
- #709 
- `saleor backup list`
- `saleor backup create`
- `saleor backup remove`
- `saleor backup show`
-
> Use organization backup endpoint
