saleor/cli

src/graphql/AppInstall.ts, src/lib/common.ts
* read provided manifestURL
* pass permissions from manifest to mutation
=> Refactor doSaleorAppInstall

src/cli/app/create.ts
I would like to be able to use this variable in the app template to link to various parts of the dashboard
=> Add host URL

src/cli/checkout/deploy.ts
=> Add summary to `checkout deploy`

src/cli/dev/index.ts, src/cli/dev/info.ts, src/lib/common.ts
Inspired by
https://app.clickup.com/2549495/v/dc/2dtqq-13601/2dtqq-3021
https://app.clickup.com/t/2549495/SALEOR-7097
=> Add `dev info` command

src/cli/checkout/deploy.ts
Updated the summary message after checkout deployment with steps to integrate checkout SPA with React storefront.
=> SALEOR-7580 Update summary to checkout deploy

src/cli/app/generate.ts, src/cli/webhook/create.ts, src/lib/util.ts
https://app.clickup.com/t/2549495/SALEOR-7209
=> Remove ANY_EVENTS from `webhook create`

src/cli/webhook/list.ts
https://app.clickup.com/t/2549495/SALEOR-6756
=> Improve messages for `webhook list`

src/cli/app/permission.ts, src/cli/webhook/create.ts
https://app.clickup.com/t/2549495/SALEOR-7573
=> Improve multiselects messages

src/cli/app/permission.ts, src/lib/got.ts, src/lib/queryEnvironment.ts
https://app.clickup.com/t/2549495/SALEOR-7552
=> Use basic auth for protected environments

README.md, src/cli.ts, src/cli/app/deploy.ts, src/lib/vercel.ts
Fix the critical bug in the path for setting env vars in Vercel API.
Make the next step in the process (Saleor App installation) explicit for the user. Showcase two ways of doing installing a Saleor app into a Saleor dashboard
=> Fix env path setting for Vercel API

src/graphql/SaleorAppList.ts, src/lib/util.ts
Remove SaleorApp query
https://app.clickup.com/t/2549495/SALEOR-7677
=> Change the order to DESC for SaleorAppList

src/cli/env/remove.ts, src/lib/response.ts, src/middleware/index.ts, src/types.ts
- Move verification logic from `env remove` to useEnvironment middleware
- Allow to pass environment option/positional by name
- Introduce spinner for better UX
- Show custom error message for missing env
=> Verify environment presence in the useEnvironment middleware

src/lib/config.ts
=> Make it easier to read `.config/saleor.json`

src/cli/app/deploy.ts, src/lib/vercel.ts
- set `nextjs` as default framework in case it's not available yet
- handle `id` and `uid` as deployment id
- extract common display of URLs
- improve Vercel error handling
=> Improve deployment edge cases

package.json, pnpm-lock.yaml, src/lib/vercel.ts, test/vercel.test.ts
=> Add initial setup for tests with `vitest`

src/cli/app/deploy.ts
It's blocked by https://github.com/saleor/saleor-app-klaviyo/pull/20
=> Remove old environment variables names

src/cli/app/create.ts
=> Provide more descriptive info when creating an app.

src/cli/app/deploy.ts, src/lib/common.ts
=> Display the error message if the wrong directory

src/cli/app/deploy.ts
* the fetch api body data type must match "Content-Type" header
=> Add missing header in `app deploy`

src/cli/app/create.ts, src/cli/app/deploy.ts, src/cli/app/install.ts, src/lib/common.ts, src/lib/util.ts
Fixes #317 
- #317 
- create a new Saleor App
- deploy it to Vercel
- and install it in your dashboard of choice
=> Eliminate the dependency on `.env`

src/cli/app/create.ts, src/cli/app/deploy.ts, src/cli/app/generate.ts, src/cli/app/install.ts, src/cli/app/list.ts, src/cli/app/permission.ts, src/cli/app/token.ts, src/cli/app/tunnel.ts, src/cli/backup/create.ts, src/cli/backup/list.ts, src/cli/backup/restore.ts, src/cli/backup/show.ts, src/cli/checkout/deploy.ts, src/lib/index.ts
Adding the `debug` statements In `app`, `backup` & `checkout` commands.
- #314 
NA
=> Add `debug` statments

src/cli/app/deploy.ts, src/cli/checkout/deploy.ts, src/cli/dev/prepare.ts, src/cli/webhook/edit.ts, src/lib/queryEnvironment.ts
**I want to merge this PR**:  to fix the code for TypeScript 4.8
NA 
NA
=> Fix the code for TypeScript 4.8

src/cli/app/deploy.ts
**I want to merge this PR to *** fix the URL parsing of GitHub repositories
- Fixes #327
-
=> Fix the URL parsing for GitHub repositories

src/cli/storefront/create.ts
**I want to merge this PR because**
It aligns `storefront create` with `react-storefront` recent changes
- 
-
=> Update `storefront create` with `react-storefront`

src/cli/app/deploy.ts
**I want to merge this PR because: **
It fixes destructuring but in triggerDeploymentInVercel in `app deploy`
- 
-
=> Fix triggerDeploymentInVercel in `app deploy`

.github/ISSUE_TEMPLATE/cli-bug-report.md
=> Update issue templates

src/cli/app/deploy.ts
**I want to merge this PR** to fix a bug
- #350 
-
=> Fix empty env variable message box

src/cli/app/permission.ts, src/cli/app/token.ts
**I want to merge this PR** to fix missing `import` statements
- 
-
=> Fix missing import statments

package.json, pnpm-lock.yaml, src/cli/info.ts, tsconfig.json
=> Make an experimental single file build for the CLI

src/cli/info.ts, tsconfig.json
**I want to merge this PR** to fix bundle with JSON for `esbuild`
- #253 
-
=> Fix the `json` include approach

package.json, scripts/binary.js
**I want to merge this PR to** fix the 1.15 RC release
**Note:** Merging to `release-1-15` branch.
- 
-
=> Fix binary install to only use Node modules

src/cli.ts
**I want to merge this PR to** fix shebang and make it work on *nix systems.
- NA
-
=> Fix the shebang setup

.github/workflows/pr.yml, .prettierignore, test/__snapshots__/vercel.test.ts.snap
It adds CICD check for lint & test + add missing configuration
- 
-
=> Add CICD check for test and lint

.github/ISSUE_TEMPLATE/cli-bug-report.md
Hints should be visible for reporters, not left in actual issue
- 
-
=> Update issue template

src/cli.ts, src/cli/register.ts
- https://github.com/saleor/saleor-cli/issues/349
-
=> Change '/register' to '/signup'

src/cli/dev/prepare.ts
=> Update `dev prepare` with new build command

package.json
- it fixes the `watch` in the development using `esbuild`
- NA
-
=> Adjust the `watch` to the `esbuild` setup

src/cli/app/deploy.ts
- it infers the domain via a middleware
- #379
-
=> Make `app deploy` to infer the instance domain

src/cli/info.ts, src/cli/login.ts
- https://github.com/saleor/saleor-cli/issues/348
-
=> `saleor login` should give additional info 

src/lib/util.ts
**I want to merge this PR because:** it improves the `contentBox` header line to fit whole screen
- NA
-
=> Improve `contentBox` header

src/middleware/index.ts
- it fixes how `argv` is passed to `yargs` middleware when these are automatically composed
- Batch Mode
-
=> Fix the `yargs` middleware composition

.github/PULL_REQUEST_TEMPLATE.md, .gitignore
- it improves the formatting in the PR template
NA
-
=> Improve the PR template

src/cli/app/deploy.ts, src/cli/storefront/deploy.ts, src/lib/deploy.ts
- it fixes re-deployment of apps 
- NA
Re - deploy a saleor app, eg:
1. `saleor app create`
2.  `cd created-app`
3. `saleor app deploy`
4. `saleor app deploy`
=> Fix `app deploy` re-deployment

docs/app.md, docs/checkout.md, docs/storefront.md
- it updates `docs` with changes for `deploy` commands
- https://github.com/saleor/saleor-cli/issues/386
- NA
=> Update docs for `deploy` commands

src/lib/vercel.ts
- It shows the more descriptive message including the build URL for failed Vercel deployment
- https://github.com/saleor/saleor-cli/issues/395
-
=> Show more descriptive error for failed Vercel deployment

src/cli/app/deploy.ts, src/cli/checkout/index.ts, src/cli/storefront/create.ts, src/cli/storefront/deploy.ts, src/cli/storefront/index.ts
- it allows to directly set the Saleor API URL for the `storefront` and `checkout` commands
- #321 
-
=> Direct Saleor URL in storefront and checkout

src/cli/storefront/create.ts
- it fixes the `store create --demo` by adding interactivity
- fixes #407
-
=> Fix the `store --demo` creation

test/functional/app/deploy.test.ts, test/functional/checkout/deploy.test.ts, test/functional/environment/show.test.ts, test/functional/project/create.test.ts, test/functional/project/list.test.ts, test/functional/storefront/create.test.ts, test/functional/storefront/deploy.test.ts, test/helper.ts
- It adds new tests which are checking if new project is added,removed and if lists includes created project.
- https://github.com/saleor/saleor-cli/issues/402
-
=> Add project tests

src/cli/checkout/deploy.ts, src/cli/storefront/deploy.ts
- it fixes how the Saleor API instance domain is assigned during the deployment flow
- #408 
-
=> Fix the instance URL assignment flow

src/cli/app/index.ts, src/cli/app/install.ts, src/cli/app/tunnel.ts, src/cli/app/uninstall.ts, src/lib/common.ts, src/middleware/index.ts
- it simplifies the flow for `app tunnel` - no app install when the tunnel starts
- it adds explicit `app uninstall`
- #305
-
=> Simplify the `app tunnel` and adds `app uninstall`

test/functional/environment/show.test.ts
- it improves the test for the `environment show` command
- NA
- `pnpm vitest run test/functional/environment/show.test.ts`
=> Improve `env show` functional test

package.json, src/cli.ts, src/middleware/index.ts
- it checks if there's Internet connection before running a command
- https://github.com/saleor/saleor-cli/issues/417
-
=> Online checker middleware

src/cli/app/create.ts, src/cli/app/deploy.ts, src/cli/app/token.ts, src/cli/app/tunnel.ts, src/cli/env/create.ts, src/lib/deploy.ts, src/lib/util.ts
It removes boxen boxes with contentBox thus enabling multiline links
- https://github.com/saleor/saleor-cli/issues/376
- https://github.com/saleor/saleor-cli/issues/220
- 
Changed commands
- `saleor app create`
- `saleor app deploy`
- `saleor app token`
- `saleor env create`
=> Use contentBox instead of boxen

package.json, pnpm-lock.yaml, src/cli.ts, src/cli/app/deploy.ts, src/cli/app/token.ts, src/lib/deploy.ts, src/lib/util.ts
- it removes an unnecessary dependency to make the bundle smaller
- NA
-
=> Remove `boxen` from dependencies

.github/workflows/tests-nightly.yml
- It introduces workflow for running tests nightly
- NA
- NA
=> Introduce tests-nightly GH workflow

.github/workflows/tests-nightly.yml, package.json, test/helper.ts
- it modifies the tests-nightly workflow in order to trigger functional tests on CI
- NA
- NA
=> Modify tests-nightly workflow run cmd

test/functional/environment/create.test.ts, test/functional/environment/list.test.ts, test/organization/show.test.ts
-  it's add new test which is adding new env list/show. 
https://github.com/saleor/saleor-cli/issues/426
- https://www.notion.so/saleor/Show-an-organization-list-3b5a1540edf14cea8af81ead07927909
-
=> add env tests and org show test

package.json
- it sets the semver numeric package version
- https://github.com/saleor/saleor-cli/issues/437
- `pnpm build`
- `node dist/saleor.js info` or any other Caleor CLI command
=> Use proper syntax for package version

.github/workflows/prepare-release.yml
- it opens a draft release with autogenerate changelogs for commit
- #239 
- Run from the `Actions` tab
=> GitHub Action flow for the draft release

.github/workflows/tests-nightly.yml, src/lib/deploy.ts, test/functional/app/deploy.test.ts, test/functional/checkout/deploy.test.ts, test/functional/environment/create.test.ts, test/functional/project/create.test.ts, test/functional/storefront/a_info.test.ts, test/functional/storefront/create.test.ts, test/functional/storefront/deploy.test.ts, test/helper.ts, test/vercel.test.ts
It enables to run tests-nightly workflow on GA. 
GH_TOKEN secret is required to be put into Actions secrets. It should contain Personal Access Token with the `repo`, `workflow`, ` delete_repo`  and `read:org` scopes
- https://github.com/saleor/devtools-integration-tests/issues/4
-
=> Improve tests-nightly

src/cli/app/uninstall.ts, src/lib/common.ts, src/lib/util.ts
- it makes uninstalling Saleor Apps only by ID
- #446
- `app uninstall <ID>`
- `app uninstall <name>`
=> Uninstall apps only by ID

src/cli/app/list.ts, src/lib/common.ts
- it fixes the `app list` to use the `--url` argument
- NA
- `app list` with `--url`
=> `app list` can use the direct Saleor URL

test/helper.ts
It updates the `testOrganization` for functional tests.
- NA
- NA
=> Update testOrganization for functional tests

README.md
- it documents ENV variables in README
- https://github.com/saleor/saleor-cli/issues/275
- NA
=> Document ENV variables in README

src/cli/app/token.ts
- it fixes the type issues for `app token`
- #459
- `app token`
=> Fix the type for `app token`

src/cli.ts, src/cli/app/uninstall.ts, src/lib/common.ts, src/lib/util.ts
- it adds error handling to `app uninstall`
- it fixes the CLI doc strings for `app uninstall`
- #446 
- #447
- `app uninstall <dummy ID>`
- `app uninstall` (without arguments)
=> Add error handling & docs to `app uninstall`

docs/backup.md, src/cli/backup/index.ts, src/cli/backup/remove.ts, src/cli/backup/show.ts, src/lib/index.ts
- it introduces the `backup remove` command for the better management of backups through Saleor CLI 
- NA
- `saleor backup remove backup-key`
=> Introduce `backup remove` command

src/cli/app/deploy.ts
- it fixes the missing fetch for some instances
- NA
- `saleor app deploy`
=> Add missing fetch for `app deploy`

test/functional/environment/create.test.ts, test/functional/project/create.test.ts, test/functional/storefront/create.test.ts, test/functional/storefront/deploy.test.ts, test/helper.ts
- it introduces test optimizations for CI
- #436 
- NA
=> Improve tests nightly

test/functional/backup/restore.test.ts
- it introduces test for `backup restore`
- NA
- `RUN_FUNCTIONAL_TESTS=true pnpm vitest run test/functional/backup/restore.test.ts`
=> Introduce backup functional tests

src/cli/info.ts, src/cli/status.ts, src/lib/queryEnvironment.ts, test/functional/app/deploy.test.ts, test/functional/environment/create.test.ts, test/functional/environment/list.test.ts, test/functional/environment/show.test.ts, test/functional/storefront/deploy.test.ts, test/helper.ts
- It improves mocks for CI for functional tests
- https://github.com/saleor/saleor-cli/issues/448
-
=> Mock improvements for tests nightly

src/cli/app/list.ts
- it enables json output for `app list` command
- https://github.com/saleor/saleor-cli/issues/409
- `saleor app list --json`
=> Enable json output for `app list` command

.github/workflows/tests-nightly.yml, package.json, test/clear_cloud.test.ts, test/functional/backup/restore.test.ts, test/functional/environment/create.test.ts, test/functional/environment/list.test.ts, test/functional/environment/show.test.ts, test/functional/project/create.test.ts, test/functional/storefront/create.test.ts, test/functional/storefront/deploy.test.ts, test/helper.ts
- it moves cleaning the staging cloud to a separate job and adds some adjustments for CI env
- https://github.com/saleor/saleor-cli/issues/436
-
=> Tests nightly improvements

src/cli.ts, src/cli/app/uninstall.ts
- it improves the process of uninstalling a Saleor app by providing more descriptive messages
- #475 
- `saleor app uninstall` - no arguments
- `saleor app uninstall something` - wrong ID
=> Improve the `app uninstall` process

src/middleware/index.ts
- It uses a promise-based catch to handle telemetry rejections.
- 
-
=> Handle telemetry errors

src/middleware/index.ts
- it fixes the `ping` args for the Windows
-  #428
- Run any command on Windows
=> Fix the `ping` args for Win32

src/cli/storefront/create.ts
- It replaces the SALEOR_API_URL value with the instance endpoint. In case of `--demo` flag the instance is set to the newly created demo environment.
- #509
-
=> Set instance for SALEOR_API_URL for `store create --demo`

src/cli/app/list.ts, src/lib/common.ts
- it fixes the instance endpoint substitution for the App list query
- #511 
- Start the tunnel with `app tunnel` and pass `--url` to the Saleor Cloud instance
=> Fix the instance endpoint for the App list query

package.json, pnpm-lock.yaml, src/cli/app/list.ts, src/lib/common.ts
- it updates dependencies
- (Maintenance)
- NA
=> Maintenance: Updating dependencies

package.json, pnpm-lock.yaml, src/cli/backup/remove.ts, src/cli/dev/prepare.ts, src/cli/env/create.ts, src/cli/env/switch.ts, src/cli/organization/remove.ts, src/cli/organization/switch.ts, src/cli/project/remove.ts, src/cli/storefront/create.ts, src/cli/webhook/edit.ts, src/lib/common.ts, src/lib/util.ts, src/middleware/index.ts
- It uses `log-symbols` pkg in order to handle characters fallback for Windows CMD as it only supports a limited character set.
- #516 
-
=> Use log-symbols to print symbols

.eslintrc.json, src/middleware/index.ts
-  it fixes the eslint issues in the middleware
- 
-
=> Fix eslint issues

README.md
- it updates the release process in the README - the release branch naming changed
- NA
- NA
=> Update the release process in the README

.github/ISSUE_TEMPLATE/config.yaml
- It adds link to GitHub Discussions in Issue create form
none
=> Add link to discussions

src/cli/github/login.ts, src/cli/login.ts, src/cli/register.ts, src/cli/vercel/login.ts, src/lib/common.ts, src/lib/util.ts
- it verifies the ability to open URL
- #548 
- `saleor login`
- `saleor github login`
- `saleor vercel login`
- `saleor register`
=> Detect open executable to handle headless env

src/cli/app/tunnel.ts
- it simplifies `ngrok` integration
- NA
- `saleor app tunnel --use-ngrok`
=> Use ngrok failover for app tunnel

src/cli.ts, src/cli/app/token.ts, src/middleware/index.ts
- it fixes the piping for `saleor app token`
- #550 
- `saleor app token --environment XXXX --app-id YYYY --short`
- `saleor app token --environment XXXX --app-id YYYY --short | pbcopy`
=> Fix piping for `app token`

src/lib/instance.ts, src/middleware/index.ts, src/types.ts
- it implements `organization` and `environment` extraction from the `instance` parameter. 
- #569 569
- `saleor app install --instance=SALEOR_INSTANCE_URL`
=> Extract params from instance URL

src/cli/app/generate.ts
=> Fix missing import

.husky/pre-commit, docs/README.md, src/cli/dev/docs.ts, src/cli/dev/index.ts
- it adds a new command `dev docs` which generates documentation
- it extends husky to update docs on the `pre-commit` hook
- #559 
- `saleor dev docs`
=> Auto generate docs with `docs` command & husky

src/cli.ts
- it improves the Sentry configuration by capturing only non-development issues, i.e. production or staging
- #369
- NA
=> Refine the Sentry capture mechanism

src/lib/common.ts
- Add optional chaining on cache as it may be `undefined`
- https://github.com/saleor/saleor-cli/actions/runs/3648600324/jobs/6162209347
-
=> Add optional chaining on cache

docs/README.md, src/cli/app/deploy.ts
I want to remove `app deploy` in https://github.com/saleor/saleor-cli/pull/605
For next version I'd like to print deprecation message before it gets removed
- 
-
=> Add deprecation note to app deploy

docs/README.md, src/cli/app/tunnel.ts, src/cli/webhook/dryRun.ts
- it sets ngrok as default tunnel
=> Use ngrok as the default tunnel

src/cli/dev/info.ts, src/cli/info.ts, src/cli/status.ts
- it fixes and unifies how `package.json` is imported
- NA
- NA
=> Fix import JSON

src/cli/dev/info.ts, src/cli/open.ts, src/cli/register.ts, src/cli/status.ts, src/lib/download.ts
- it fixes the `import` paths
- NA
- NA
=> Fix the `import` paths

src/cli/configure.ts, src/cli/env/create.ts, src/cli/register.ts, src/cli/webhook/create.ts, src/lib/deploy.ts, src/lib/util.ts
- It extracts common confirm format for prompts
- https://github.com/saleor/saleor-cli/issues/219
- `saleor env create`
- `saleor webhook create`
- `saleor configure`
- `saleor register`
=> Extract common confirm format

README.md
- it makes `README` slightly better
- NA
- NA
=> Add cool icon to the README

README.md
- it adds a better quality logo
- NA
- NA
=> Add a better quality logo

src/cli/login.ts
- it improves the auth process
- #632 
- NA
=> Improve the auth process

src/lib/deploy.ts
- it adds 2 new required environment variables to the checkout deployment  - `APL` & `SALEOR_APP_JWKS`
- NA
- `saleor store deploy --with-checkout`
- `saleor checkout deploy`
=> Add new ENVs for checkout deployment

src/cli/app/tunnel.ts
- it handles changes in the ngrok behavior and the free account limitations errors
- https://github.com/saleor/saleor-cli/issues/631
=> Update `app tunnel` to match ngrok changes

src/cli/app/template.ts, src/cli/storefront/create.ts, src/lib/git.ts
- it changes the way the git repository is initialized. For better compatibility with older versions of git the `--initial-branch` flag has been dropped
- it unifies the `setupGitRepository` into one source
- #663 
- `saleor app template`
- `saleor example`
- `saleor storefront create`
=> Handle older versions of git for `git init`

src/aws-exports-prod.ts
- It changes the auth endpoint
- 
-
=> Change the auth endpoint

docs/README.md, src/cli/app/tunnel.ts, src/middleware/index.ts
- it improves the `app tunnel` description & binary missing error message
- NA
=> Improve missing ngrok binary behaviour

src/cli/env/promote.ts, src/cli/storefront/create.ts, src/lib/index.ts, src/lib/util.ts, src/middleware/index.ts, src/types.ts
- It improves typings in util
- #465 
- NA
=> Reduce any's in util

package.json, pnpm-lock.yaml, test/functional/storefront/create.test.ts
- it wraps the `url` in the `storefront create` test 
- it sets the proper exit code for `storefront create` for mocked tests
- it downgrades the `nanoid` to fix the `getRandomValues` error in the GH Actions tests
- NA
- re-run GH Actions `nightly-tests`
=> Tests fixes

src/cli.ts
- it handles `Invalid token.` API error. In such cases user is being logged out and informed to login.
- #686
- trigger any action with an expired or invalid token in the config
=> Handle `Invalid token.` error

docs/cli/overview.mdx, src/cli/dev/docs.ts
- it updates example `instance` URL in the docs overview
- NA
- NA
=> Update example `instance` URL in the docs overview

.github/workflows/tests-nightly.yml
=> Fix tests workflow after relasing 1.41 version

README.md
- I want better describe steps involved in releasing CLI
- 
-
=> Improve release documentation

README.md, docs/README.md, docs/cli/commands/telemetry.mdx, src/cli.ts, src/cli/configure.ts, src/cli/telemetry/disable.ts, src/cli/telemetry/enable.ts, src/cli/telemetry/status.ts, src/config.ts, src/lib/config.ts, src/middleware/index.ts
- it removes code for telemetry handling. Saleor no longer gathers telemetry and commands failed due to missing dependent service
- 
-
=> remove telemetry
